DDGLC/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'

  namespace :project do
    get '/about',   to: 'about#index'
    get '/staff',   to: 'staff#index'
    get '/contact', to: 'contact#index'
    get '/imprint', to: 'imprint#index'
  end

  get '/lexicon/about', to: 'lexicon#about'
  get '/lexicon/', to: 'lexicon#about'

  resources :lemmas, path: '/lexicon/lemmas'
  resources :lemma_comments, path: '/lexicon/lemma_comments'
  resources :sublemmas, path: '/lexicon/sublemmas'
  resources :sublemma_comments, path: '/lexicon/sublemma_comments'
  resources :usages, path: '/lexicon/usages'
  resources :usage_comments, path: '/lexicon/usage_comments'

  resources :part_of_speeches, path: 'lexicon/pos'
  resources :languages, path: '/lexicon/languages'
  resources :semantic_fields, path: '/lexicon/semantic_fields'
  resources :usage_categories, path: '/lexicon/usage_categories'
  resources :distinction_tiers, path: '/lexicon/distinction_tiers'

  resources :users

  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  get  '/logout', to: 'sessions#destroy'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

DDGLC/app/models/sublemma.rb
class Sublemma < ApplicationRecord
  include SublemmaFilter

  belongs_to :part_of_speech, optional: true
  belongs_to :language, optional: true
  belongs_to :lemma, optional: true
  belongs_to :created_by, class_name: 'User'
  belongs_to :updated_by, class_name: 'User'

  has_many :sublemma_comments
  has_many :usages

  paginates_per 10

  validates :label, presence: true
  validates :hierarchy, allow_blank: true, format: {with: /\A[IVX]+[.]?[A-Z]?[.]?[0-9]*\z/}

  NIL_ATTRS = %w[part_of_speech_id language_id hierarchy loaned_form lemma_id].freeze
  before_save :nil_if_blank, :squish_values

  def comments_for(field)
    comments = sublemma_comments.where(field: field)
    comments ||= []
    comments
  end

  def nil_if_blank
    NIL_ATTRS.each{ |attr| self[attr] = nil if self[attr].blank? }
  end
end

DDGLC/app/controllers/sublemmas_controller.rb
class SublemmasController < ApplicationController
  load_and_authorize_resource

  def index
    persistence_id = params[:reset_filter] == 'true' ? false : 'sublemmas#index'

    @filterrifc = initialize_filterrific(
        Sublemma,
        params[:filterrific],
        select_options: {
          sorted_by: Sublemma.options_for_sorted_by,
          with_any_language_ids: Language.options_for_select,
          with_any_created_by_ids: User.options_for_select('sublemmas', 'created_by_id'),
          with_any_updated_by_ids: User.options_for_select('sublemmas', 'updated_by_id'),
          with_part_of_speech_id: PartOfSpeech.options_for_select
        },
        persistence_id: persistence_id
    ) or return


    @sublemmas = @filterrifc.find.page(params[:page])

  rescue ActiveRecord::RecordNotFound => e
    redirect_to(reset_filterrific_url(format: :html)) and return
  end

  def show
    @sublemma = Sublemma.find(params[:id])
  end

  def new
    @sublemma = Sublemma.new(lemma_id: params[:lemma_id])
  end

  def edit
    @sublemma = Sublemma.find(params[:id])
  end

  def create
    @sublemma = Sublemma.new(sublemma_params)
    @sublemma.created_by = current_user
    @sublemma.updated_by = current_user
    if @sublemma.save
      flash[:notice] = 'Successfully created new Coptic sublemma.'
      redirect_to sublemma_path(@sublemma)
    else
      flash[:error] = 'Could not create Coptic sublemma.'
      render 'new'
    end
  end

  def update
    @sublemma = Sublemma.find(params[:id])
    if @sublemma.update(sublemma_params)
      flash[:notice] = 'Successfully updated Coptic sublemma.'
      redirect_to sublemma_path(@sublemma)
    else
      flash[:error] = 'Could not update Coptic sublemma.'
      render 'edit'
    end
  end

  def destroy
    @sublemma = Sublemma.find(params[:id])
    SublemmaComment.where(sublemma_id: @sublemma.id).delete_all
    @sublemma.destroy
    redirect_to sublemmas_path
  end

  private

  def sublemma_params
    params.require(:sublemma).permit(:label, :part_of_speech_id, :language_id, :lemma_id,
                                     :hierarchy, :loaned_form, :activated)
  end
end

DDGLC/app/views/sublemmas/_filter.html.haml
= form_for_filterrific @filterrifc do |f|
  .row
    .col-md-6.form-group
      %label.filter-label Sort by
      = f.select :sorted_by, @filterrifc.select_options[:sorted_by], { include_blank: '...' }, class: 'form-control'
    .col-md-5.col-md-offset-1.form-group
      = link_to reset_filterrific_url, role: 'button', class: 'btn', style: 'padding: 0px' do
        %p.filter-label Reset filters
        = fa_icon 'times', class: 'fa-2x'
  %hr
  .row
    .col-md-12.form-group
      %label.filter-label Coptic Sublemma
      = f.text_field :search_for_label, class: 'filterrific-periodically-observed form-control', placeholder: '...'
  .row
    .col-md-12.form-group
      %label.filter-label
        = fa_icon('link', class: 'text-muted panel-lemma-icon')
        Greek Lemma
      = f.text_field :with_lemma_label, class: 'filterrific-periodically-observed form-control', placeholder: '...'
  .row
    .col-md-12.form-group
      %label.filter-label
        = fa_icon('tag', class: 'text-muted panel-lemma-icon')
        Part of Speech
      = f.select :with_any_part_of_speech_ids, @filterrifc.select_options[:with_part_of_speech_id], { include_blank: '...' }, class: 'form-control'
  .row
    .col-md-12.form-group
      %label.filter-label
        = fa_icon('sitemap', class: 'text-muted panel-lemma-icon')
        Hierarchy
      = f.text_field :search_for_hierarchy, class: 'filterrific-periodically-observed form-control', placeholder: '...'
  .row
    .col-md-12.form-group
      %label.filter-label
        = fa_icon('globe', class: 'text-muted panel-lemma-icon')
        Language
      = f.select :with_any_language_ids, @filterrifc.select_options[:with_any_language_ids], { include_blank: '...' }, class: 'form-control'
  %hr
  .row
    .col-md-12.form-group
      %label.filter-label
        = fa_icon('user-o', class: 'text-muted panel-lemma-icon')
        Created by
      = f.select :with_any_created_by_ids, @filterrifc.select_options[:with_any_created_by_ids], { include_blank: '...' }, class: 'form-control'
  .row
    .col-md-12.form-group
      %label.filter-label
        = fa_icon('user-o', class: 'text-muted panel-lemma-icon')
        Last update by
      = f.select :with_any_updated_by_ids, @filterrifc.select_options[:with_any_updated_by_ids], { include_blank: '...' }, class: 'form-control'
  %hr
    .row
      .col-md-12
        %small
          You can use
          %code
            *
          as a placeholder for an arbitrary number of characters in text fields. For instance,
          %code
            *(*)
          searches for text which contains an opening parenthesis and a closing parenthesis; whereby
          %code
            (*)
          returns text which starts with an opening parenthesis and contains a closing one.

DDGLC/app/views/sublemmas/_form.html.haml
= bootstrap_form_for(@sublemma, layout: :horizontal, label_col: 'col-md-2', control_col: 'col-md-4') do |f|
  = f.text_field :label
  = f.collection_select :part_of_speech_id, PartOfSpeech.all.order(:label), :id, lambda{|pos| pos.label.titleize}, include_blank: true, help: @sublemma.comments_for('part_of_speech').map{|c| c.created_by.code + ': ' + c.content}.join("\n")
  = f.collection_select :language_id, Language.all.order(:code), :id, :code, include_blank: true
  - if @sublemma.lemma
    = f.hidden_field :lemma_id
    = f.static_control label: 'Greek Lemma' do
      .coptic-greek.adjust-line= Lemma.find_by_id(@sublemma.lemma.id)&.label
  - else
    = f.text_field :lemma_id, label: 'Greek Lemma'
  = f.text_field :loaned_form, help: @sublemma.comments_for('loaned_form').map{|c| c.created_by.code + ': ' + c.content}.join("\n")
  = f.text_field :hierarchy, help: 'Schema: I.A.0'
  %br
  = f.form_group do
    = f.submit 'Save Coptic Sublemma', class: 'btn btn-primary btn-block'

DDGLC/app/views/sublemmas/_list.html.haml
.row
  .col-md-12.text-right.text-muted
    %p
      - if @sublemmas.total_count != Sublemma.count
        showing
        = pluralize @sublemmas.total_count, 'Coptic sublemma', 'Coptic sublemmas'
        after filtering
        = "(#{(100 * @sublemmas.total_count.to_f / Sublemma.count).round(1)}%)"
      - else
        showing all
        = pluralize Sublemma.count, 'Coptic sublemma', 'Coptic sublemmas'
.row
  .col-md-12
    %ul
      - @sublemmas.each do |sublemma|
        %li
          .panel.panel-default.panel-lemma
            .row
              .col-md-12
                %span.coptic-greek.lemma-label= link_to sublemma.label, sublemma_path(sublemma)
            .row
              .col-md-4
                .row
                  .col-md-12
                    = fa_icon('link', class: 'text-muted panel-lemma-icon')
                    - if sublemma.lemma.present?
                      %span.coptic-greek{style: 'font-size: 15px'}= link_to sublemma.lemma&.label, lemma_path(sublemma.lemma)
                .row
                  .col-md-12
                    = fa_icon('sitemap', class: 'text-muted panel-lemma-icon')
                    = optional_field sublemma.hierarchy
              .col-md-5
                .row
                  .col-md-12
                    = fa_icon('tag', class: 'text-muted panel-lemma-icon')
                    = optional_field sublemma.part_of_speech&.label&.titleize
                .row
                  .col-md-12
                    = fa_icon('globe', class: 'text-muted panel-lemma-icon')
                    = optional_field sublemma&.language&.code
              .col-md-3
                .row
                  .col-md-12
                    usages:
                    = sublemma.usages.count
                .row
                  .col-md-12
                    = sublemma.updated_at.strftime('update: %b %Y')


.row
  .col-md-12.text-center
    = paginate @sublemmas, window: 3

DDGLC/app/views/sublemmas/_previews.html.haml
- if sublemmas.empty?
  = '-'
- else
  - show_lemma = true if show_lemma.nil?
  %table.table.table-hover.table-previews
    - sublemmas.order(:lemma_id, :hierarchy).each do |sublemma|
      %tr
        - if show_lemma
          %td.coptic-greek.adjust-line= link_to optional_field(sublemma.lemma&.label), lemma_path(sublemma.lemma)
        %td= optional_field sublemma.hierarchy
        %td= optional_field sublemma.part_of_speech&.label&.titleize
        %td= link_to fa_icon('eye'), sublemma_path(sublemma)

DDGLC/app/views/sublemmas/edit.html.haml
- content_for :page_title do
  Coptic Sublemma

%section.col-md-8.col-md-offset-2
  .container
    = render partial: 'shared/lexicon_navigation', locals: {title: 'Edit'}
    = render 'form'

DDGLC/app/views/sublemmas/index.html.haml
- content_for :page_title do
  Coptic Sublemmas

%section.col-md-8.col-md-offset-2
  .container
    = render partial: 'shared/lexicon_navigation', locals: {is_sublemma: true}


    .row
      .col-md-8
        .panel-default.panel-lexicon#filterrific_results
          = render partial: 'list'

      .col-md-4
        .panel.panel-default.panel-lexicon
          .panel-body
            = link_to new_sublemma_path do
              = fa_icon('plus')
              %b Create New Coptic Sublemma

        .panel.panel-default.panel-lexicon
          .panel-body
            = render partial: 'filter'

DDGLC/app/views/sublemmas/index.js.erb
<% js = escape_javascript(
  render(partial: 'sublemmas/list')
) %>
$("#filterrific_results").html("<%= js %>");

DDGLC/app/views/sublemmas/new.html.haml
- content_for :page_title do
  Coptic Sublemma

%section.col-md-8.col-md-offset-2
  .container
    = render partial: 'shared/lexicon_navigation', locals: {title: 'Create'}
    = render 'form'

DDGLC/app/views/sublemmas/show.html.haml
- content_for :page_title do
  Coptic Sublemma

%section
  .container
    = render partial: 'shared/lexicon_navigation', locals: {title: @sublemma.label}

    .row
      .col-md-6
        .panel-group

          -# sublemma, pos
          .panel.panel-default.panel-lexicon
            .panel-body
              .row.lexicon-field
                .col-md-3.lexicon-field-attribute
                  Sublemma
                .col-md-8.lexicon-field-value.coptic-greek
                  = @sublemma.label

              .row.lexicon-field
                .col-md-3.lexicon-field-attribute
                  Part of Speech
                .col-md-8.lexicon-field-value
                  = optional_field @sublemma.part_of_speech&.label&.titleize
                .col-md-1
                  = comment_button '#partofspeechComment'
              = render partial: 'comments/show_comments', locals: {commented_entry: @sublemma, field: 'part_of_speech'}
              = render partial: 'comments/add_comment', locals: {target_id: 'partofspeechComment', field: 'part_of_speech', commented_entry_id: @sublemma.id, comment: SublemmaComment.new}


          -# language
          - if @sublemma.language.present?
            .panel.panel-default.panel-lexicon
              .panel-body
                .row.lexicon-field
                  .col-md-3.lexicon-field-attribute
                    Language
                  .col-md-8.lexicon-field-value
                    = optional_field @sublemma.language.code


          -# greek lemma, loaned form, hierarchy
          .panel.panel-default.panel-lexicon
            .panel-body
              .row.lexicon-field
                .col-md-3.lexicon-field-attribute
                  Greek Lemma
                .col-md-8.lexicon-field-value.coptic-greek
                  - if @sublemma.lemma.present?
                    = link_to @sublemma.lemma.label, lemma_path(@sublemma.lemma)
                  - else
                    = '-'

              .row.lexicon-field
                .col-md-3.lexicon-field-attribute
                  Loaned Form
                .col-md-8.lexicon-field-value
                  =  optional_field @sublemma.loaned_form
                .col-md-1
                  = comment_button '#loanedFormComment'
              = render partial: 'comments/show_comments', locals: {commented_entry: @sublemma, field: 'loaned_form'}
              = render partial: 'comments/add_comment', locals: {target_id: 'loanedFormComment', field: 'loaned_form', commented_entry_id: @sublemma.id, comment: SublemmaComment.new}

              .row.lexicon-field
                .col-md-3.lexicon-field-attribute
                  Hierarchy
                .col-md-8.lexicon-field-value
                  =  optional_field @sublemma.hierarchy


          -# owner, updater, further comments
          .panel.panel-default.panel-lexicon
            .panel-body
              .row.lexicon-field
                .col-md-3.lexicon-field-attribute
                  Creation
                .col-md-8.lexicon-field-value
                  = "#{@sublemma.created_at.strftime('%b %e, %Y')} by #{@sublemma.created_by.code}"
              .row.lexicon-field
                .col-md-3.lexicon-field-attribute
                  Last Update
                .col-md-8.lexicon-field-value
                  - if @sublemma.created_at == @sublemma.updated_at
                    = '-'
                  - else
                    = "#{@sublemma.updated_at.strftime('%b %e, %Y')} by #{@sublemma.updated_by.code}"
              .row.lexicon-field
                - comments = @sublemma.comments_for('sublemma')
                .col-md-3.lexicon-field-attribute
                  Comments
                .col-md-9
                  - if comments.empty?
                    = '-'
                  - else
                    - comments.sort_by{|c| c[:created_at]}.each do |comment|
                      %blockquote.lexicon-field-comment.text-muted
                        %p= comment.content
                        %small
                          = "#{comment.created_by.code}, #{comment.updated_at.strftime('%b %Y')}"
                          - if comment.created_by == current_user
                            = link_to sublemma_comment_path(comment), method: :delete, data: {confirm: 'Are you sure?'} do
                              = fa_icon('trash')
                    %br
              = render partial: 'comments/add_comment', locals: {target_id: 'generalComment', field: 'sublemma', commented_entry_id: @sublemma.id, comment: SublemmaComment.new}

          -# actions
          - unless current_user.guest?
            .panel.panel-default.panel-lexicon
              .panel-heading
                .panel-title Actions
              .panel-body
                .row
                  .col-md-3.text-center
                    = link_to edit_sublemma_path(@sublemma) do
                      = fa_icon('edit')
                      Edit
                  .col-md-3.text-center
                    = comment_button '#generalComment', ' Comment'
                  .col-md-3.text-center
                    = link_to new_usage_path(sublemma_id: @sublemma.id) do
                      = fa_icon('plus')
                      Usage
                  .col-md-3.text-center
                    - if current_user.admin?
                      = link_to sublemma_path(@sublemma), method: :delete, data: {confirm: 'Are you sure?'} do
                        = fa_icon('trash')
                        Delete
                    - else
                      %i
                        %small.text-muted No permisson for delete.


      .col-md-6
        -# coptic usages
        .panel.panel-default.panel-lexicon
          .panel-heading
            .panel-title
              = link_to 'Coptic Usages', usages_path
              = "(#{@sublemma.usages.count})"
          .panel-body
            = render partial: 'usages/previews', locals: {usages: @sublemma.usages, show_sublemma: false}