DDGLC/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'

  namespace :project do
    get '/about',   to: 'about#index'
    get '/staff',   to: 'staff#index'
    get '/contact', to: 'contact#index'
    get '/imprint', to: 'imprint#index'
  end

  get '/lexicon/about', to: 'lexicon#about'
  get '/lexicon/', to: 'lexicon#about'

  resources :lemmas, path: '/lexicon/lemmas'
  resources :lemma_comments, path: '/lexicon/lemma_comments'
  resources :sublemmas, path: '/lexicon/sublemmas'
  resources :sublemma_comments, path: '/lexicon/sublemma_comments'
  resources :usages, path: '/lexicon/usages'
  resources :usage_comments, path: '/lexicon/usage_comments'

  resources :part_of_speeches, path: 'lexicon/pos'
  resources :languages, path: '/lexicon/languages'
  resources :semantic_fields, path: '/lexicon/semantic_fields'
  resources :usage_categories, path: '/lexicon/usage_categories'
  resources :distinction_tiers, path: '/lexicon/distinction_tiers'

  resources :users

  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  get  '/logout', to: 'sessions#destroy'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

DDGLC/app/views/shared/_flash_message.html.haml
- if flash[:success] or flash[:notice] or flash[:warning] or flash[:error]
  .container
    .row.row-flash-message
      .col-md-12
        -if flash[:notice]
          .alert.alert-success.fade.in
            =flash[:notice]
            %button{:class => 'close', 'data-dismiss' => 'alert', :href =>'#'}
              &times
        -if flash[:error]
          .alert.alert-danger.fade.in
            =flash[:error]
            %button{:class => 'close', 'data-dismiss' => 'alert', :href =>'#'}
              &times
        -if flash[:success]
          .alert.alert-success.fade.in
            =flash[:success]
            %button{:class => 'close', 'data-dismiss' => 'alert', :href =>'#'}
              &times
        -if flash[:warning]
          .alert.alert-warning.fade.in
            =flash[:warning]
            %button{:class => 'close', 'data-dismiss' => 'alert', :href =>'#'}
              &times

DDGLC/app/views/shared/_footer.html.haml
%footer
  .container
    .row
      .col-md-10.text-muted
        Contact:        
        Prof Dr. Tonio Sebastian Richter
        = mail_to 'ddglc@gmx.de', fa_icon('envelope')
        |
        Freie Universität Berlin
        |
        Fachbereich Geschichts- und Kulturwissenschaften
        |
        Ägyptologisches Seminar
      .col-md-2
        = link_to 'Imprint', project_imprint_path

DDGLC/app/views/shared/_lexicon_navigation.html.haml
- title ||= nil
- is_lexicon ||= false
- is_lemma ||= false
- is_sublemma ||= false
- is_usage ||= false
.page-header
  %h1.lexicon-headline
    - if title
      %span= title
    %span
      %small= link_to 'Lexicon', '/lexicon/about' unless is_lexicon
      = "Lexicon" if is_lexicon
    %span
      %small= link_to 'Greek Lemma', lemmas_path unless is_lemma
      = 'Greek Lemma' if is_lemma
    %span
      %small= link_to 'Coptic Sublemma', sublemmas_path unless is_sublemma
      = 'Coptic Sublemma' if is_sublemma
    %span
      %small= link_to 'Coptic Usage', usages_path unless is_usage
      = 'Coptic Usage' if is_usage

DDGLC/app/views/shared/_navigation.html.haml
= navbar fixed: :top, id: 'mainNav' do
  = navbar_header brand: "#{image_tag('logo2.jpg', height: '30px')} DDGLC", brand_link: root_path
  = navbar_collapse do
    = navbar_group align: 'right', id: 'menu' do
      = navbar_item 'Home', root_path
      = navbar_dropdown 'Project' do
        = navbar_item 'About',   project_about_path
        = navbar_item 'Staff',   project_staff_path
        = navbar_item 'Contact', project_contact_path
      - if logged_in?
        = navbar_dropdown "Lexicon" do
          = navbar_item 'About', '/lexicon/about'
          = navbar_dropdown_divider
          = navbar_item 'Greek Lemma', lemmas_path
          = navbar_item 'Coptic Sublemma', sublemmas_path
          = navbar_item 'Coptic Usage', usages_path
        -#= navbar_dropdown 'Attestations' do
        -#  = navbar_item 'foo', '/foo'
        -#= navbar_dropdown 'Manuscript/ Texts' do
        -#  = navbar_item 'foo', '/foo'
        -#= navbar_dropdown 'Bibliography' do
        -#  = navbar_item 'foo', '/foo'
        - if logged_in_as_manager_or_admin?
          = navbar_dropdown fa_icon('cog') do
            -#= navbar_item 'Settings', '/settings'
            -#= navbar_dropdown_divider
            -#= navbar_item "Admin Dashboard", '/admin'
            = navbar_item 'User Management', users_path
        - if logged_in?
          = navbar_item "Log out #{fa_icon('sign-out')}", logout_path, method: :delete
        - else
          = navbar_item "#{fa_icon('sign-in')} Log in", login_path

DDGLC/app/views/shared/_project_navigation.html.haml
- is_about ||= false
- is_staff ||= false
- is_contact ||= false
.page-header
  %h1.project-headline
    %span
      %small= link_to 'About', '/project/about' unless is_about
      = "About" if is_about
    %span
      %small= link_to 'Staff', '/project/staff' unless is_staff
      = "Staff" if is_staff
    %span
      %small= link_to 'Contact', '/project/contact' unless is_contact
      = "Contact" if is_contact